name: publish social bridge API

on: workflow_dispatch

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Upload to Maven repository
        env:
          REGISTRY_TOKEN: ${{ secrets.MVN_PUBLISH_TOKEN }}
        run: |
          ./gradlew social-bridge:publish